In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./Containmnet_Policy_Cleaned.csv')

FileNotFoundError: [Errno 2] No such file or directory: './Containmnet_Policy_Cleaned.csv'

In [ ]:
df.head()

,CountryName,RegionName,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,...,C6_Stay at home requirements,C6_Flag,C7_Restrictions on internal movement,C7_Flag,C8_International travel controls,E1_Income support,E1_Flag,E2_Debt/contract relief,E3_Fiscal measures,E4_International support
0,Aruba,NaN,2020-01-01,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0
1,Aruba,NaN,2020-01-02,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0
2,Aruba,NaN,2020-01-03,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0
3,Aruba,NaN,2020-01-04,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0
4,Aruba,NaN,2020-01-05,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0

In [ ]:
df.columns

Index(['CountryName', 'RegionName', 'Date', 'C1_School closing', 'C1_Flag',
       'C2_Workplace closing', 'C2_Flag', 'C3_Cancel public events', 'C3_Flag',
       'C4_Restrictions on gatherings', 'C4_Flag', 'C5_Close public transport',
       'C5_Flag', 'C6_Stay at home requirements', 'C6_Flag',
       'C7_Restrictions on internal movement', 'C7_Flag',
       'C8_International travel controls', 'E1_Income support', 'E1_Flag',
       'E2_Debt/contract relief', 'E3_Fiscal measures',
       'E4_International support'],
      dtype='object')

In [ ]:
df.CountryName.unique()

array(['Aruba', 'Afghanistan', 'Angola', 'Albania', 'Andorra',
       'United Arab Emirates', 'Argentina', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Burkina Faso',
       'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas',
       'Bosnia and Herzegovina', 'Belarus', 'Belize', 'Bermuda',
       'Bolivia', 'Brazil', 'Barbados', 'Brunei', 'Bhutan', 'Botswana',
       'Central African Republic', 'Canada', 'Switzerland', 'Chile',
       'China', "Cote d'Ivoire", 'Cameroon',
       'Democratic Republic of Congo', 'Congo', 'Colombia', 'Comoros',
       'Cape Verde', 'Costa Rica', 'Cuba', 'Cyprus', 'Czech Republic',
       'Germany', 'Djibouti', 'Dominica', 'Denmark', 'Dominican Republic',
       'Algeria', 'Ecuador', 'Egypt', 'Eritrea', 'Spain', 'Estonia',
       'Ethiopia', 'Finland', 'Fiji', 'France', 'Faeroe Islands', 'Gabon',
       'United Kingdom', 'Georgia', 'Ghana', 'Guinea', 'Gambia', 'Greece',
       'Greenland', 'Guatemala', 'Guam', 'Guyana', 'Hong Kong',
       'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'India',
       'Ireland', 'Iran', 'Iraq', 'Iceland', 'Israel', 'Italy', 'Jamaica',
       'Jordan', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyz Republic',
       'Cambodia', 'Kiribati', 'South Korea', 'Kuwait', 'Laos', 'Lebanon',
       'Liberia', 'Libya', 'Liechtenstein', 'Sri Lanka', 'Lesotho',
       'Lithuania', 'Luxembourg', 'Latvia', 'Macao', 'Morocco', 'Monaco',
       'Moldova', 'Madagascar', 'Mexico', 'Mali', 'Malta', 'Myanmar',
       'Mongolia', 'Mozambique', 'Mauritania', 'Mauritius', 'Malawi',
       'Malaysia', 'Namibia', 'Niger', 'Nigeria', 'Nicaragua',
       'Netherlands', 'Norway', 'Nepal', 'New Zealand', 'Oman',
       'Pakistan', 'Panama', 'Peru', 'Philippines', 'Papua New Guinea',
       'Poland', 'Puerto Rico', 'Portugal', 'Paraguay', 'Palestine',
       'Qatar', 'Kosovo', 'Romania', 'Russia', 'Rwanda', 'Saudi Arabia',
       'Sudan', 'Senegal', 'Singapore', 'Solomon Islands', 'Sierra Leone',
       'El Salvador', 'San Marino', 'Somalia', 'Serbia', 'South Sudan',
       'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini',
       'Seychelles', 'Syria', 'Chad', 'Togo', 'Thailand', 'Tajikistan',
       'Turkmenistan', 'Timor-Leste', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Taiwan', 'Tanzania', 'Uganda', 'Ukraine',
       'Uruguay', 'United States', 'Uzbekistan', 'Venezuela',
       'United States Virgin Islands', 'Vietnam', 'Vanuatu', 'Yemen',
       'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
#Calculating the average of the stringency index for each country for each month 

df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

df['Month'] = df['Month'].astype(str)
df['Year'] = df['Year'].astype(str)

df['Month_Year'] = df['Month'] + '-' + df['Year']

df['Month_Year'] = pd.to_datetime(df['Month_Year'], format='%m-%Y')

df['Month_Year'] = df['Month_Year'].dt.strftime('%m-%Y')

df

,CountryName,RegionName,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,...,C7_Flag,C8_International travel controls,E1_Income support,E1_Flag,E2_Debt/contract relief,E3_Fiscal measures,E4_International support,Month,Year,Month_Year
0,Aruba,NaN,2020-01-01,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1,2020,01-2020
1,Aruba,NaN,2020-01-02,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1,2020,01-2020
2,Aruba,NaN,2020-01-03,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1,2020,01-2020
3,Aruba,NaN,2020-01-04,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1,2020,01-2020
4,Aruba,NaN,2020-01-05,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1,2020,01-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221827,Zimbabwe,NaN,2021-12-07,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,12,2021,12-2021
221828,Zimbabwe,NaN,2021-12-08,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,12,2021,12-2021
221829,Zimbabwe,NaN,2021-12-09,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,12,2021,12-2021
221830,Zimbabwe,NaN,2021-12-10,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,12,2021,12-2021
221831,Zimbabwe,NaN,2021-12-11,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,12,2021,12-2021

In [ ]:
df.drop(['E1_Income support', 'E1_Flag','E2_Debt/contract relief', 'E3_Fiscal measures','E4_International support', 'Month', 'Year'], axis=1, inplace=True)

In [ ]:
#Calculating the average for each of the containment measures for each country for each month

df.head()

,CountryName,RegionName,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,C4_Flag,C5_Close public transport,C5_Flag,C6_Stay at home requirements,C6_Flag,C7_Restrictions on internal movement,C7_Flag,C8_International travel controls,Month_Year
0,Aruba,NaN,2020-01-01,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,01-2020
1,Aruba,NaN,2020-01-02,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,01-2020
2,Aruba,NaN,2020-01-03,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,01-2020
3,Aruba,NaN,2020-01-04,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,01-2020
4,Aruba,NaN,2020-01-05,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,01-2020

In [ ]:
# List of columns to average
columns_to_average = [
    'C1_School closing', 'C2_Workplace closing', 'C3_Cancel public events',
    'C4_Restrictions on gatherings', 'C5_Close public transport',
    'C6_Stay at home requirements', 'C7_Restrictions on internal movement',
    'C8_International travel controls'
]

# Group by 'CountryName' and 'Month_Year' and calculate the mean for the specified columns
average_values = df.groupby(['CountryName', 'Month_Year'])[columns_to_average].mean().reset_index()

# Display the resulting DataFrame
average_values

,CountryName,Month_Year,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls
0,Afghanistan,01-2020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Afghanistan,01-2021,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
2,Afghanistan,02-2020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.724138
3,Afghanistan,02-2021,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
4,Afghanistan,03-2020,1.741935,0.774194,2.000000,0.000000,0.258065,0.451613,0.225806,3.000000
...,...,...,...,...,...,...,...,...,...,...
4459,Zimbabwe,10-2021,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,0.354839,1.000000
4460,Zimbabwe,11-2020,1.266667,1.000000,2.000000,3.000000,1.000000,2.000000,2.000000,2.000000
4461,Zimbabwe,11-2021,0.966667,1.000000,1.000000,3.000000,1.000000,1.000000,1.600000,1.033333
4462,Zimbabwe,12-2020,1.000000,1.451613,2.000000,3.000000,1.000000,2.000000,2.000000,2.000000
4463,Zimbabwe,12-2021,0.000000,0.545455,0.545455,1.636364,0.545455,0.545455,0.545455,1.090909

In [ ]:
# Step 1: Convert 'Month_Year' to datetime format
average_values['Month_Year'] = pd.to_datetime(average_values['Month_Year'], format='%m-%Y')

# Step 2: Sort the values by 'CountryName' and the properly formatted 'Month_Year'
average_values = average_values.sort_values(by=['CountryName', 'Month_Year'])

# (Optional) If you want to convert 'Month_Year' back to a string after sorting, you can do so:
average_values['Month_Year'] = average_values['Month_Year'].dt.strftime('%m-%Y')

# Display the sorted DataFrame
average_values

,CountryName,Month_Year,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls
0,Afghanistan,01-2020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Afghanistan,02-2020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.724138
4,Afghanistan,03-2020,1.741935,0.774194,2.000000,0.000000,0.258065,0.451613,0.225806,3.000000
6,Afghanistan,04-2020,3.000000,3.000000,2.000000,3.466667,2.000000,2.000000,1.633333,3.000000
8,Afghanistan,05-2020,3.000000,3.000000,2.000000,4.000000,2.000000,2.000000,2.000000,3.000000
...,...,...,...,...,...,...,...,...,...,...
4455,Zimbabwe,08-2021,2.806452,2.000000,2.000000,3.000000,0.258065,2.000000,2.000000,2.000000
4457,Zimbabwe,09-2021,1.400000,1.266667,1.766667,3.000000,1.000000,1.766667,1.200000,1.766667
4459,Zimbabwe,10-2021,1.000000,1.000000,1.000000,3.000000,1.000000,1.000000,0.354839,1.000000
4461,Zimbabwe,11-2021,0.966667,1.000000,1.000000,3.000000,1.000000,1.000000,1.600000,1.033333
4463,Zimbabwe,12-2021,0.000000,0.545455,0.545455,1.636364,0.545455,0.545455,0.545455,1.090909

In [ ]:
# Sum the values of C1 to C8 columns for each row
average_values['Total'] = average_values[columns_to_average].sum(axis=1)

# Sort the DataFrame by the 'Total' column in descending order
sorted_average_values = average_values.sort_values(by='Total', ascending=False)

# Drop the 'Total' column if you don't need it anymore
sorted_average_values = sorted_average_values.drop(columns=['Total'])

# Display the sorted DataFrame
sorted_average_values.CountryName.unique()[:10]

array(['Philippines', 'Chile', 'Honduras', 'Kazakhstan',
       'Kyrgyz Republic', 'Libya', 'Georgia', 'El Salvador', 'Argentina',
       'Serbia'], dtype=object)

In [ ]:
cleaned_df = sorted_average_values[sorted_average_values['CountryName'].isin(['Philippines', 'Chile', 'Honduras', 'Kazakhstan',
       'Kyrgyz Republic', 'Libya', 'Georgia', 'El Salvador', 'Argentina',
       'Serbia'])]

In [ ]:
cleaned_df

,CountryName,Month_Year,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls
3174,Philippines,04-2020,3.0,3.0,2.0,4.0,2.0,3.0,2.0,4.0
827,Chile,06-2021,3.0,3.0,2.0,4.0,2.0,3.0,2.0,4.0
1760,Honduras,05-2020,3.0,3.0,2.0,4.0,2.0,3.0,2.0,4.0
2094,Kazakhstan,04-2020,3.0,3.0,2.0,4.0,2.0,3.0,2.0,4.0
1758,Honduras,04-2020,3.0,3.0,2.0,4.0,2.0,3.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...
818,Chile,02-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1775,Honduras,12-2021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2111,Kazakhstan,12-2021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2352,Libya,01-2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2231,Kyrgyz Republic,12-2021,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Step 1: Convert 'Month_Year' to datetime format
cleaned_df['Month_Year'] = pd.to_datetime(cleaned_df['Month_Year'], format='%m-%Y')

# Step 2: Sort the values by 'CountryName' and the properly formatted 'Month_Year'
cleaned_df = cleaned_df.sort_values(by=['CountryName', 'Month_Year'])

# (Optional) If you want to convert 'Month_Year' back to a string after sorting, you can do so:
cleaned_df['Month_Year'] = cleaned_df['Month_Year'].dt.strftime('%m-%Y')

# Display the sorted DataFrame
cleaned_df.reset_index(drop=True, inplace=True)

cleaned_df.CountryName.unique()

C:\Users\shrey\AppData\Local\Temp\ipykernel_8332\501738942.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_df['Month_Year'] = pd.to_datetime(cleaned_df['Month_Year'], format='%m-%Y')

array(['Argentina', 'Chile', 'El Salvador', 'Georgia', 'Honduras',
       'Kazakhstan', 'Kyrgyz Republic', 'Libya', 'Philippines', 'Serbia'],
      dtype=object)

In [ ]:
cleaned_df

,CountryName,Month_Year,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls
0,Argentina,01-2020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Argentina,02-2020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Argentina,03-2020,1.548387,1.258065,1.354839,1.677419,0.580645,1.258065,0.774194,2.387097
3,Argentina,04-2020,3.000000,3.000000,2.000000,4.000000,2.000000,2.866667,1.866667,4.000000
4,Argentina,05-2020,3.000000,2.354839,2.000000,4.000000,2.000000,2.000000,1.677419,4.000000
...,...,...,...,...,...,...,...,...,...,...
235,Serbia,08-2021,1.000000,1.000000,1.000000,2.000000,0.000000,1.000000,0.000000,1.000000
236,Serbia,09-2021,1.000000,1.000000,1.000000,2.000000,0.300000,1.000000,0.300000,1.000000
237,Serbia,10-2021,1.000000,1.000000,1.000000,2.000000,1.000000,0.129032,0.129032,1.870968
238,Serbia,11-2021,1.500000,0.500000,1.000000,2.000000,0.500000,0.500000,0.000000,2.000000
239,Serbia,12-2021,0.181818,0.000000,0.090909,0.181818,0.000000,0.090909,0.000000,0.181818

In [ ]:
cleaned_df.CountryName.unique()
cleaned_df.to_csv('./pcp/Containment_Policy_Cleaned.csv', index=False)
cleaned_df.CountryName.unique()

array(['Argentina', 'Chile', 'El Salvador', 'Georgia', 'Honduras',
       'Kazakhstan', 'Kyrgyz Republic', 'Libya', 'Philippines', 'Serbia'],
      dtype=object)